/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java 
   application
    id("buildlogic.java-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
implementation("org.seleniumhq.selenium:selenium-java:4.23.0");

}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
    mainClass.set("App")
}
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}